### PR TITLE
Strawberry Pudding Popsicles

### PR DESCRIPTION
**Pull request by jennank**
Adding strawberry pudding popsicles to the dessert category.

### CODE REVIEW

**Comment by jennank** [comment]
@bernardopacini here is the url for the popsicle reference: [Fresh Strawberry and Vanilla Pudding Pops](https://www.maebells.com/fresh-strawberry-and-vanilla-pudding-pops/)

**Comment by bernardopacini** [comment]
> @bernardopacini here is the url for the popsicle reference: [Fresh Strawberry and Vanilla Pudding Pops](https://www.maebells.com/fresh-strawberry-and-vanilla-pudding-pops/)

I take back what I said offline about this and using bibtex. Would you mind updating this and just writing the reference yourself?

**Comment by jennank** [comment]
@bernardopacini are we good to merge this in now?

**Comment by bernardopacini** [comment]
Looks good to me! Merging.

**Review by bernardopacini — APPROVED** [review]

**Pull request merged**
