### PR TITLE
Fixing missing ingredient in steps of carbonara recipe

### PR DESCRIPTION
**Pull request by bernardopacini**
The carbonara recipe mentions heavy cream as an ingredient, but it does not say when to include it in the steps. Fixing that oversight here.

### CODE REVIEW

**Comment by jennank** [comment]
The build is failing because of a [python update](https://github.com/urllib3/urllib3/issues/2168). We tried to fix this following the [RTD migration guide](https://urllib3.readthedocs.io/en/latest/v2-migration-guide.html) but no luck. Need to keep debugging.

**Comment by bernardopacini** [comment]
RTD has fixed the issue and it looks like everything is back up and running again. This PR is good to go @jennank.

**Comment by bernardopacini** [comment]
@jennank is this good to go?

**Review by jennank — APPROVED** [review]
Looks good to me!

**Pull request merged**
