### PR TITLE
Butternut squash soup incoming

### PR DESCRIPTION
**Pull request by eytanadler**
Take a nice picture once its done to add!

### CODE REVIEW

**Comment by bernardopacini** [comment]
Thanks for adding this recipe!

**Comment by bernardopacini** [comment]
Git history got a bit confusing here and rebased to drop two commits as discussed offline. Setting a reminder to remake, taste-test-approve, and merge this in!

**Comment by bernardopacini** [comment]
Delicious tonight! Taste test approved.

I think the only things we said that are missing are:

- [x] Adding heading to soup page
- [x] Adding garlic to ingredients
- [x] Specifying how much salt / pepper to add
- [x] Adding yourself to the README as a contributor

Am I missing anything from dinner tonight? Would you (@eytanadler) mind filling these in so we can go ahead and merge it? Thanks again for the contribution!

**Comment by eytanadler** [comment]
I think it's ready to go now!

**Review by jennank — APPROVED** [review]
This was delicious! Looks great to me, merging in now.

**Pull request merged**
